### ISSUE TITLE
Treasury functionality in frontend

### ISSUE THREAD

**Issue by tensojka** [CarmineOptions/konoha#117]
We need to add the following functionality to the frontend:

When adding a new proposal, there should be multiple new options
- to distribute a given token from the treasury to a given address.
- it should be explained that to distribute tokens, it should be sent to an external defispring-like contract, the user should be pointed [here](https://github.com/starknetfndn/defispring) for documentation.
- deposit tokens to Nostra/zkLend (arbitrary proposal that calls treasury should be used for this)
- withdraw tokens from Nostra/zkLend. The user will supply all the required parameters for the proposal.

When opening a already live proposal that distributes funds from Treasury, it should be shown what parameters it has – is it a proposal to distribute tokens, to withdraw from Nostra/zkLend?

**Comment by Jemiiah** [comment]
I would love to work on this issue @tensojka

**Comment by petersdt** [comment]
Hi @tensojka, 
if this issue is still open for contribution I would love to contribute to this project.
I am a frontend developer with experience using JavaScript, typescript, frontend framework and typed programming language like Cairo.
[OnlyDust profile](https://app.onlydust.com/settings/profile)

**Comment by Oshioke-Salaki** [comment]
Hello please can i be assigned this?

**Comment by ScottyDavies** [comment]
can i take up this issue, i am first time contributor and would love to be part of this ecosystem

**Comment by ScottyDavies** [comment]
Still open?

**Comment by tensojka** [comment]
Done in #137 and #127 and #126
