### ISSUE TITLE
sncast deployment script for Konoha

### ISSUE THREAD

**Issue by tensojka** [CarmineOptions/konoha#129]
Either use https://foundry-rs.github.io/starknet-foundry/starknet/script.html or document how to deploy Konoha.

**Comment by Oshioke-Salaki** [comment]
Pl

**Comment by raizo07** [comment]
@tensojka Can I be assigned to work on this?

**Comment by tensojka** [comment]
Please... https://konoha.vote/docs/CONTRIBUTING.html

**Comment by tensojka** [comment]
Okay @Oshioke-Salaki , assigned you. Will unassign you if there is no PR by tomorrow EOD.

**Comment by tensojka** [comment]
Closing as it's not yet possible with sncast scripts to detect whether a given contract class is already declared and avoid failing in that case.
