### ISSUE TITLE
Standardize the codebase in the repository so that it is independent of the Carmine Options AMM and can be used by any protocol

### ISSUE THREAD

**Issue by MarekHauzr** [CarmineOptions/konoha#51]
Essentially remove all the mentions of CARM/Carmine and similar.

Part of the result should be that any protocol will be able to release their own governance.

**Comment by StarkFishinator** [comment]
Hi, I would like to try this one !

**Comment by MarekHauzr** [comment]
Hi, super awesome.

Could you share your tg/discord handle so that we can stream line the conversation?

**Comment by tensojka** [comment]
Okay, this will be done by making everything into a Component.
