### ISSUE TITLE
Document how proposals work

### ISSUE THREAD

**Issue by tensojka** [CarmineOptions/konoha#68]
Core proposal functionality should be documented from a usage/deployment perspective.

- various contract types
- adding custom proposals
- arbitrary proposals
- when do proposals pass, express proposal passing, the different quorums

Code documentation (to be generated in the future) is outside the scope of this task.

**Comment by Xaxxoo** [comment]
Hi, is this open ? I'll like to work on it.

**Comment by juandiegocv27** [comment]
Hi, I'd love to contribute to this issue, please assign it to me #68, @tensojka

**Comment by tensojka** [comment]
Closing this as duplicate of #83

cc @juandiegocv27

**Comment by juandiegocv27** [comment]
oh ok :(
