### ISSUE TITLE
ODHack: Deposits to support Nostra Lending Pools

### ISSUE THREAD

**Issue by tensojka** [CarmineOptions/konoha#80]
Extend treasury.cairo to support deposit and withdraw to/from Nostra. support for multiple tokens (ETH, USDC, USDT, STRK, WBTC)

You can use the feature of depositing into Carmine liquidity pools in treasury.cairo as inspiration.

### Definition of Done

The Cairo code works as expected, has nearly full test coverage, is reasonably documented (docstrings or similar suffice) and readable. An end-to-end integration test is provided.

**Comment by Iwueseiter** [comment]
hi

**Comment by tensojka** [comment]
@Iwueseiter  Refer to https://github.com/CarmineOptions/konoha/blob/master/CONTRIBUTING.md please, you are missing an estimated delivery timeline. I would also appreciate a brief summary of your relevant skills, though not strictly required.

It would also be nice of you to join the Konoha Dev Telegram group for faster communication.

**Comment by Iwueseiter** [comment]
I have joined the Telegram group and I left a message there.
I work on this between 4 to 5 working day max.
Thank you.

**Comment by tensojka** [comment]
Assigned @juandiegocv27 as @Iwueseiter already has a task

**Comment by juandiegocv27** [comment]
@tensojka so I have the issue, right?

**Comment by tensojka** [comment]
@juandiegocv27 Yes

@Iwueseiter Sorry. I picked Juan also because he provided more detailed information about him. There will be testing tasks opened tomorrow

**Comment by juandiegocv27** [comment]
@tensojka who should I talk to for questions about my issue?

**Comment by juandiegocv27** [comment]
@tensojka Im already doing this issue, could you assign in to me here please

**Comment by tensojka** [comment]
@juandiegocv27 You are assigned already

**Comment by juandiegocv27** [comment]
@tensojka sorry, please asign the issue to someone else, the time limit of the od hack its so near an for me to finish this task it implement more days

**Comment by saimeunt** [comment]
@tensojka I'd like to try this one, hopefully I can get it done by the end of ODHack.
I have experience with Cairo development and I'll make sure to respect the contributing guidelines and acceptance criterias.

**Comment by tensojka** [comment]
@saimeunt Assigned you, good luck!
