### ISSUE TITLE
ODHack: Documentation

### ISSUE THREAD

**Issue by tensojka** [CarmineOptions/konoha#83]
Write a chapter of documentation as a markdown file in docs/ directory. One chapter = one component. First study the code, then document how to use it and how to customize it, if applicable. This documentation should be aimed at protocols looking to use Konoha and assume knowledge of Cairo Components.

Expected skill level: Junior Cairo developer

This issue can be assigned to multiple persons, multiple people can work on different parts of the docs in parallel.

### Definition of Done

The documentation is clear, readable, not obviously written by AI, documents all available customizations when using the component and give simple usage instructions. 

### Assignment

This issue will be assigned to multiple contributors as each works on their own chapter.

Assigned so far:

- airdrop @Joy-Adah 
- proposals @raizo07 
- token @AnoukRImola 
- vesting @more-of-odeh 
- upgrades @Ayoazeez26 
- treasury @fishonamos

**Comment by Iwueseiter** [comment]
hi

**Comment by raizo07** [comment]
@tensojka I'll like to work on this, kindly assign

**Comment by Gift-Naomi** [comment]
hi

**Comment by kateberryd** [comment]
I would like to contribute to this

**Comment by AnoukRImola** [comment]
Hi!  @tensojka please can I work on this?  :)

**Comment by tensojka** [comment]
Could each of you select a specific chapter you would like to contribute first?

@AnoukRImola @raizo07 @Iwueseiter 

@kateberryd @Gift-Naomi You can document the parts of the code you'll be working on and interacting with. If you wish to claim other parts, I will slightly prefer other contributors as you already have a task assigned.

**Comment by gidson5** [comment]
Hy @tensojka can I get assigned  a part of this one please,I haven't been assigned any task yet

**Comment by tensojka** [comment]
@gidson5 Please select a specific chapter you would like to contribute first.

**Comment by Joy-Adah** [comment]
Hi @tensojka I'll love to work on the airdrop chapter.

**Comment by tensojka** [comment]
Okay @Joy-Adah , assigning you on the airdrop chapter. https://github.com/starknetfndn/defispring might come handy as that contract is similar and somehow documented.

**Comment by Xaxxoo** [comment]
Hi @tensojka, may I work on constants chapter?

**Comment by raizo07** [comment]
@tensojka I'll like to work on the proposals chapter

**Comment by Joy-Adah** [comment]
@tensojka thanks!

**Comment by AnoukRImola** [comment]
@tensojka I would like to work on the token chapter :)

**Comment by tensojka** [comment]
@Xaxxoo No as that is not really an appropriate chapter for user-facing documentation.

**Comment by Xaxxoo** [comment]
> @Xaxxoo No as that is not really an appropriate chapter for user-facing documentation.

Can I take types chapter ?

**Comment by more-of-odeh** [comment]
can i be assigned this?

**Comment by gidson5** [comment]
Hy @tensojka I'll love to work on the staking chapter

**Comment by gidson5** [comment]
> @gidson5 Please select a specific chapter you would like to contribute first

 @tensojka Can I please work on the staking chapter?

**Comment by tensojka** [comment]
@Xaxxoo 

The types chapter is also not suited for user-facing documentation.

Given the recent misalignments with our documentation requirements, we will not assign you further tasks in Konoha.

**Comment by tensojka** [comment]
@raizo07 Great, you have been assigned the proposals chapter

**Comment by tensojka** [comment]
@AnoukRImola you have been assigned the token chapter. Document both the voting token (locked) and the floating token please.

**Comment by more-of-odeh** [comment]
@tensojka can i be assigned the Vesting chapter?

**Comment by tensojka** [comment]
Note that I have now merged scaffolding for the mdbook in which you will work in #75 .

@AnoukRImola @raizo07 @Joy-Adah

**Comment by Ayoazeez26** [comment]
@tensojka Can I work on the upgrades chapter?

**Comment by tensojka** [comment]
@gidson5 Staking is not yet finished, I'm working on it, I will finish it in the next few days. Once the code is done, you can start working on the documentation.

**Comment by tensojka** [comment]
@more-of-odeh Yes. Please coordinate with @Jemiiah who has #79 as streaming in vesting should be documented too.

**Comment by tensojka** [comment]
@Ayoazeez26 Definitely yes, that's I would say the complex chapter. Make sure to document how custom proposals work. Refer to https://github.com/CarmineOptions/amm-governance for an example of a deployment of Konoha that uses custom proposals.

**Comment by gidson5** [comment]
> @gidson5 Staking is not yet finished, I'm working on it, I will finish it in the next few days. Once the code is done, you can start working on the documentation.

Alright cool.also it'll be nice if I'd be notified when it's ready so I can start.please

**Comment by fishonamos** [comment]
Will love to work on [treasury.cairo](https://github.com/CarmineOptions/konoha/blob/master/src/treasury.cairo)

**Comment by adrianvrj** [comment]
Hello, is there any chapter left I could work on?

**Comment by tensojka** [comment]
Everyone, please note that the documentation should be user-level, not code-level. Imagine you are a protocol that is evaluating the use of a specific Konoha component for your usecase. Write what they might need to find in the docs – what can you and what can't you use the <chapter> for? Can you integrate it with Konoha only, do you need all of Konoha, does it depend on other Konoha functionality, or can it be used with other solutions too?

Again, this is not documentation for someone who will be adjusting the code!

**Comment by raizo07** [comment]
@tensojka I'll send a PR for review today.

**Comment by tensojka** [comment]
Done in https://github.com/CarmineOptions/konoha/pull/111
