### ISSUE TITLE
ODHack: Fix vote delegation

### ISSUE THREAD

**Issue by tensojka** [CarmineOptions/konoha#90]
There are already some delegation functionalities in `proposals.cairo`, but they are commented out. Get them to work and add tests, see `tests/README.md` for description of required tests

**Comment by Jemiiah** [comment]
Pls I would love to work on this @tensojka

**Comment by EjembiEmmanuel** [comment]
@tensojka I'd love to work on this

**Comment by tensojka** [comment]
@EjembiEmmanuel You have been assigned. Please open a draft PR so I can see your progress once you have something.

**Comment by tensojka** [comment]
Done in #100
