### ISSUE TITLE
ODHack: Implement Unit and Integration Tests for Upgrades

### ISSUE THREAD

**Issue by tensojka** [CarmineOptions/konoha#92]
### Unit Tests Implementation

Implement unit tests for the following scenarios:
- Apply a passed proposal: Ensure a proposal marked as passed is correctly applied.
- Apply already applied proposal: Ensure the contract rejects reapplying a proposal that has already been applied.
- Apply failed proposal: Ensure the contract rejects applying a proposal that did not pass.
- Apply non-existent proposal: Ensure the contract rejects applying a proposal that does not exist.
   Integration Tests Implementation

### Integration tests

- Successful contract upgrade: Simulate a successful contract upgrade via a passed proposal and verify the new implementation is in effect.
- Custom proposal execution: Simulate the execution of a custom proposal and verify the specified action is correctly performed.
- Revert on failed upgrade: Simulate an upgrade that should fail (e.g., due to invalid parameters) and verify the contract state is reverted to its pre-upgrade state.
- Event emission: Verify the appropriate events (Upgraded, etc.) are correctly emitted during successful and failed upgrade attempts.

## Documentation and Contribution Guidelines

Ensure all new tests are documented and are formatted with `scarb fmt`.

Contribution Guidelines
Please refer to [CONTRIBUTING.md](https://github.com/CarmineOptions/konoha/blob/master/docs/src/CONTRIBUTING.md) for info on how to claim the task.

Note to Contributors:

Ensure you run all tests and verify their correctness before submitting your pull request.
Include detailed descriptions and comments in your code to explain the purpose and functionality of each test.
If you encounter any issues or have questions, feel free to open an issue or reach out to me in the Telegram group.
Thank you for your contributions!

**Comment by EjembiEmmanuel** [comment]
@tensojka I'd love to work on this
